version: '3.9'
services:
  frontend:
    build: ./app
    ports:
      - 5174:5174
    platform: linux/x86_64
    working_dir: /app-frontend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:5174"] 
      timeout: 10s
      retries: 5